<?php
/**
 * ISingleton
 *
 * @category   Core
 * @package    BAZALT
 * @subpackage Interfaces
 * @copyright  2010 Equalteam
 * @license    GPLv3
 * @version    SVN: $Revision: 154 $
 * @link       http://bazalt-cms.com/
 */

/**
 * ISingleton
 *
 * @category   Core
 * @package    BAZALT
 * @subpackage Interfaces
 * @copyright  2010 Equalteam
 * @license    GPLv3
 * @version    Release: $Revision: 154 $
 */
interface ISingleton
{
}